### PR TITLE
require lsp 1.17, with inlay hints

### PR DESCRIPTION
**Pull request by c-cube**

### CODE REVIEW

**Comment by DK318** [comment]
Hey @c-cube, did you finish that PR? If you did, can you please ship it? If not, do you mind if I take care of it? I need that support for inlay hints. Thanks.

**Comment by c-cube** [comment]
Updated. Would you be amenable to trying it for a little while, with `opam pin`? I can also make a release but it's more risky.

**Comment by DK318** [comment]
Yeah, I can try it, thanks. But I'm not sure what I should check :thinking:

**Comment by c-cube** [comment]
Just that your LSP still works  with the new version :-). To see if the new inlay hints work you'd have to do a bit too much work to integrate them than I'm comfortable asking for.

**Comment by DK318** [comment]
I checked, LSP works. Thanks!

**Comment by c-cube** [comment]
Alright then, I can make a release!

**Pull request merged**
